package cn.rf.hz.web.model.gd;

import cn.rf.hz.web.model.BaseModel;

public class ParkingModel extends BaseModel {
	

		private Integer recordId;//   	private Integer parkingId;//   停车位ID(外部数据库)	private Integer areaId;//   区域ID(外部数据库)	private java.lang.Double positionX;//   	private java.lang.Double positionY;//   	private java.lang.Double positionWidth;//   	private java.lang.Double positionHeight;//   	private Long reserveTime;//   车位预留时间	private java.lang.Boolean isReserve;//   是否预留：默认 0 否	private Integer groupId;//   车位分组ID(外部数据库)	private java.util.Date updTime;//   	private Integer carParkId;//   所属停车场	public Integer getRecordId() {	    return this.recordId;	}	public void setRecordId(Integer recordId) {	    this.recordId=recordId;	}	public Integer getParkingId() {	    return this.parkingId;	}	public void setParkingId(Integer parkingId) {	    this.parkingId=parkingId;	}	public Integer getAreaId() {	    return this.areaId;	}	public void setAreaId(Integer areaId) {	    this.areaId=areaId;	}	public java.lang.Double getPositionX() {	    return this.positionX;	}	public void setPositionX(java.lang.Double positionX) {	    this.positionX=positionX;	}	public java.lang.Double getPositionY() {	    return this.positionY;	}	public void setPositionY(java.lang.Double positionY) {	    this.positionY=positionY;	}	public java.lang.Double getPositionWidth() {	    return this.positionWidth;	}	public void setPositionWidth(java.lang.Double positionWidth) {	    this.positionWidth=positionWidth;	}	public java.lang.Double getPositionHeight() {	    return this.positionHeight;	}	public void setPositionHeight(java.lang.Double positionHeight) {	    this.positionHeight=positionHeight;	}	public Long getReserveTime() {	    return this.reserveTime;	}	public void setReserveTime(Long reserveTime) {	    this.reserveTime=reserveTime;	}	public java.lang.Boolean getIsReserve() {	    return this.isReserve;	}	public void setIsReserve(java.lang.Boolean isReserve) {	    this.isReserve=isReserve;	}	public Integer getGroupId() {	    return this.groupId;	}	public void setGroupId(Integer groupId) {	    this.groupId=groupId;	}	public java.util.Date getUpdTime() {	    return this.updTime;	}	public void setUpdTime(java.util.Date updTime) {	    this.updTime=updTime;	}	public Integer getCarParkId() {	    return this.carParkId;	}	public void setCarParkId(Integer carParkId) {	    this.carParkId=carParkId;	}
	
}
